@@include('../libs/jquery/jquery.js')
@@include('../libs/uikit3/uikit.min.js')
@@include('../libs/uikit3/uikit-icons.min.js')
@@include('../libs/lightslider/lightslider.js')
@@include('../libs/swiper/swiper.js') 
@@include('../libs/fullpage/jquery.fullpage.min.js')
